CREATE TABLE user (
		id SERIAL NOT NULL,
		email VARCHAR(500) NOT NULL,
		name VARCHAR(255) NULL,
		password VARCHAR(255) NOT NULL DEFAULT "testdd",
		CONSTRAINT user_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT user_pk PRIMARY KEY (id),
		CONSTRAINT user_ak_2 UNIQUE (email) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX user_idx_1 ON user (id);
CREATE INDEX user_idx_1 ON user (email);

CREATE TABLE post (
		id SERIAL NOT NULL,
		createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
		updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
		user_id INT NOT NULL,
		CONSTRAINT post_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT post_pk PRIMARY KEY (id),
		CONSTRAINT post_user_id_fk_1 FOREIGN KEY (user) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX post_idx_1 ON post (id);
CREATE INDEX post_idx_1 ON post (user_id);

