CREATE TABLE test (
		id UUID NOT NULL DEFAULT uuid_generate_v4(),
		CONSTRAINT test_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX test_idx_1 ON test (id);

CREATE TABLE proxy (
		id SERIAL NOT NULL,
		host VARCHAR(255) NOT NULL,
		scheme UNKNOWN NOT NULL DEFAULT "http",
		port INTEGER NOT NULL DEFAULT 8080,
		username VARCHAR(255) NOT NULL DEFAULT "PRIVATEVPN_USERNAME",
		password VARCHAR(255) NOT NULL DEFAULT "PRIVATEVPN_PASSWORD",
		is_custom_provider BOOLEAN NOT NULL DEFAULT false,
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
		CONSTRAINT proxy_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT proxy_pk PRIMARY KEY (id),
		CONSTRAINT proxy_ak_2 UNIQUE (host) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT proxy_ak_3 UNIQUE (username) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT proxy_ak_4 UNIQUE (password) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX proxy_idx_1 ON proxy (id);

CREATE TABLE instagram_account (
		id SERIAL NOT NULL,
		email VARCHAR(255) NOT NULL,
		email_verified BOOLEAN NOT NULL DEFAULT false,
		CONSTRAINT instagram_account_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT instagram_account_pk PRIMARY KEY (id),
		CONSTRAINT instagram_account_ak_2 UNIQUE (email) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX instagram_account_idx_1 ON instagram_account (id);
CREATE INDEX instagram_account_idx_2 ON instagram_account (email);

CREATE TABLE account (
		id SERIAL NOT NULL,
		email VARCHAR(255) NOT NULL,
		email_verified BOOLEAN NOT NULL DEFAULT false,
		password VARCHAR(255) NULL,
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
		CONSTRAINT account_ak_1 UNIQUE (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
		CONSTRAINT account_pk PRIMARY KEY (id),
		CONSTRAINT account_ak_2 UNIQUE (email) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX account_idx_1 ON account (id);
CREATE INDEX account_idx_2 ON account (email);

