// Generated by gosql: DO NOT EDIT.
package controllers

import (
	"context"
	"database/sql"
)

type Client struct {
	db  *sql.DB
	ctx context.Context
}

type Controllers struct {
	Account                        *AccountController
	Proxy                          *ProxyController
	Credential                     *CredentialController
	Job                            *JobController
	InstagramAccount               *InstagramAccountController
	ScrapedInstagramAccount        *ScrapedInstagramAccountController
	ScrapedInstagramAccountChained *ScrapedInstagramAccountChainedController
}

func NewClient(db *sql.DB) *Controllers {
	ctx := context.Background()
	client := &Client{db: db, ctx: ctx}
	return &Controllers{

		Account:                        &AccountController{client},
		Proxy:                          &ProxyController{client},
		Credential:                     &CredentialController{client},
		Job:                            &JobController{client},
		InstagramAccount:               &InstagramAccountController{client},
		ScrapedInstagramAccount:        &ScrapedInstagramAccountController{client},
		ScrapedInstagramAccountChained: &ScrapedInstagramAccountChainedController{client},
	}
}
