// Generated by gosql: DO NOT EDIT.
package controllers

type SelectAccountColumns struct {
	Id                *bool `json:"id"`
	Name              *bool `json:"name"`
	ProfilePictureUrl *bool `json:"profilePictureUrl"`
	Email             *bool `json:"email"`
	Password          *bool `json:"password"`
	CreatedAt         *bool `json:"createdAt"`
	UpdatedAt         *bool `json:"updatedAt"`
}

type SelectProxyColumns struct {
	Id               *bool `json:"id"`
	Host             *bool `json:"host"`
	Scheme           *bool `json:"scheme"`
	Port             *bool `json:"port"`
	Username         *bool `json:"username"`
	Password         *bool `json:"password"`
	IsCustomProvider *bool `json:"isCustomProvider"`
	Account          *bool `json:"account"`
	CreatedAt        *bool `json:"createdAt"`
	UpdatedAt        *bool `json:"updatedAt"`
}

type SelectCredentialColumns struct {
	Id          *bool `json:"id"`
	CsfrToken   *bool `json:"csfrToken"`
	UserAgent   *bool `json:"userAgent"`
	AppId       *bool `json:"appId"`
	Cookie      *bool `json:"cookie"`
	InstagramId *bool `json:"instagramId"`
	CreatedAt   *bool `json:"createdAt"`
	UpdatedAt   *bool `json:"updatedAt"`
}

type SelectJobColumns struct {
	Id        *bool `json:"id"`
	Type      *bool `json:"type"`
	CreatedAt *bool `json:"createdAt"`
	UpdatedAt *bool `json:"updatedAt"`
}

type SelectInstagramAccountColumns struct {
	Id                         *bool `json:"id"`
	Username                   *bool `json:"username"`
	Password                   *bool `json:"password"`
	Country                    *bool `json:"country"`
	Active                     *bool `json:"active"`
	TotalActionsDone           *bool `json:"totalActionsDone"`
	NeedsToBeChecked           *bool `json:"needsToBeChecked"`
	LoginFailed                *bool `json:"loginFailed"`
	IsSetup                    *bool `json:"isSetup"`
	SetupTargetAccountUsername *bool `json:"setupTargetAccountUsername"`
	Proxy                      *bool `json:"proxy"`
	Credential                 *bool `json:"credential"`
	Account                    *bool `json:"account"`
	Job                        *bool `json:"job"`
	CreatedAt                  *bool `json:"createdAt"`
	UpdatedAt                  *bool `json:"updatedAt"`
}

type SelectScrapedInstagramAccountColumns struct {
	Id                    *bool `json:"id"`
	InstagramId           *bool `json:"instagramId"`
	Username              *bool `json:"username"`
	FullName              *bool `json:"fullName"`
	Biography             *bool `json:"biography"`
	FacebookId            *bool `json:"facebookId"`
	IsVerified            *bool `json:"isVerified"`
	IsPrivate             *bool `json:"isPrivate"`
	ProfilePictureUrl     *bool `json:"profilePictureUrl"`
	ExternalUrl           *bool `json:"externalUrl"`
	BusinessCategoryName  *bool `json:"businessCategoryName"`
	CategoryName          *bool `json:"categoryName"`
	IsBusinessAccount     *bool `json:"isBusinessAccount"`
	IsProfessionalAccount *bool `json:"isProfessionalAccount"`
	FollowedByCount       *bool `json:"followedByCount"`
	FollowCount           *bool `json:"followCount"`
	MediaCount            *bool `json:"mediaCount"`
	HighlightCount        *bool `json:"highlightCount"`
	HasReels              *bool `json:"hasReels"`
	ExtractedEmail        *bool `json:"extractedEmail"`
	HasManagement         *bool `json:"hasManagement"`
	Account               *bool `json:"account"`
	CreatedAt             *bool `json:"createdAt"`
	UpdatedAt             *bool `json:"updatedAt"`
}

type SelectScrapedInstagramAccountChainedColumns struct {
	Id                      *bool `json:"id"`
	InstagramId             *bool `json:"instagramId"`
	Username                *bool `json:"username"`
	FullName                *bool `json:"fullName"`
	ProfilePictureUrl       *bool `json:"profilePictureUrl"`
	ScrapedInstagramAccount *bool `json:"scrapedInstagramAccount"`
	Account                 *bool `json:"account"`
	CreatedAt               *bool `json:"createdAt"`
	UpdatedAt               *bool `json:"updatedAt"`
}
