// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dm

var TableNames = struct {
	Account                        string
	Credential                     string
	InstagramAccount               string
	Job                            string
	Proxy                          string
	SchemaMigrations               string
	ScrapedInstagramAccount        string
	ScrapedInstagramAccountChained string
}{
	Account:                        "account",
	Credential:                     "credential",
	InstagramAccount:               "instagram_account",
	Job:                            "job",
	Proxy:                          "proxy",
	SchemaMigrations:               "schema_migrations",
	ScrapedInstagramAccount:        "scraped_instagram_account",
	ScrapedInstagramAccountChained: "scraped_instagram_account_chained",
}
