// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Proxy is an object representing the database table.
type Proxy struct {
	ID               int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Host             string    `boil:"host" json:"host" toml:"host" yaml:"host"`
	Scheme           string    `boil:"scheme" json:"scheme" toml:"scheme" yaml:"scheme"`
	Port             int       `boil:"port" json:"port" toml:"port" yaml:"port"`
	Username         string    `boil:"username" json:"username" toml:"username" yaml:"username"`
	Password         string    `boil:"password" json:"password" toml:"password" yaml:"password"`
	IsCustomProvider bool      `boil:"is_custom_provider" json:"is_custom_provider" toml:"is_custom_provider" yaml:"is_custom_provider"`
	AccountID        int       `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	CreatedAt        time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *proxyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L proxyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProxyColumns = struct {
	ID               string
	Host             string
	Scheme           string
	Port             string
	Username         string
	Password         string
	IsCustomProvider string
	AccountID        string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "id",
	Host:             "host",
	Scheme:           "scheme",
	Port:             "port",
	Username:         "username",
	Password:         "password",
	IsCustomProvider: "is_custom_provider",
	AccountID:        "account_id",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

var ProxyTableColumns = struct {
	ID               string
	Host             string
	Scheme           string
	Port             string
	Username         string
	Password         string
	IsCustomProvider string
	AccountID        string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "proxy.id",
	Host:             "proxy.host",
	Scheme:           "proxy.scheme",
	Port:             "proxy.port",
	Username:         "proxy.username",
	Password:         "proxy.password",
	IsCustomProvider: "proxy.is_custom_provider",
	AccountID:        "proxy.account_id",
	CreatedAt:        "proxy.created_at",
	UpdatedAt:        "proxy.updated_at",
}

// Generated where

var ProxyWhere = struct {
	ID               whereHelperint
	Host             whereHelperstring
	Scheme           whereHelperstring
	Port             whereHelperint
	Username         whereHelperstring
	Password         whereHelperstring
	IsCustomProvider whereHelperbool
	AccountID        whereHelperint
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
}{
	ID:               whereHelperint{field: "\"proxy\".\"id\""},
	Host:             whereHelperstring{field: "\"proxy\".\"host\""},
	Scheme:           whereHelperstring{field: "\"proxy\".\"scheme\""},
	Port:             whereHelperint{field: "\"proxy\".\"port\""},
	Username:         whereHelperstring{field: "\"proxy\".\"username\""},
	Password:         whereHelperstring{field: "\"proxy\".\"password\""},
	IsCustomProvider: whereHelperbool{field: "\"proxy\".\"is_custom_provider\""},
	AccountID:        whereHelperint{field: "\"proxy\".\"account_id\""},
	CreatedAt:        whereHelpertime_Time{field: "\"proxy\".\"created_at\""},
	UpdatedAt:        whereHelpertime_Time{field: "\"proxy\".\"updated_at\""},
}

// ProxyRels is where relationship names are stored.
var ProxyRels = struct {
	Account           string
	InstagramAccounts string
}{
	Account:           "Account",
	InstagramAccounts: "InstagramAccounts",
}

// proxyR is where relationships are stored.
type proxyR struct {
	Account           *Account              `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
	InstagramAccounts InstagramAccountSlice `boil:"InstagramAccounts" json:"InstagramAccounts" toml:"InstagramAccounts" yaml:"InstagramAccounts"`
}

// NewStruct creates a new relationship struct
func (*proxyR) NewStruct() *proxyR {
	return &proxyR{}
}

func (r *proxyR) GetAccount() *Account {
	if r == nil {
		return nil
	}
	return r.Account
}

func (r *proxyR) GetInstagramAccounts() InstagramAccountSlice {
	if r == nil {
		return nil
	}
	return r.InstagramAccounts
}

// proxyL is where Load methods for each relationship are stored.
type proxyL struct{}

var (
	proxyAllColumns            = []string{"id", "host", "scheme", "port", "username", "password", "is_custom_provider", "account_id", "created_at", "updated_at"}
	proxyColumnsWithoutDefault = []string{"host", "account_id"}
	proxyColumnsWithDefault    = []string{"id", "scheme", "port", "username", "password", "is_custom_provider", "created_at", "updated_at"}
	proxyPrimaryKeyColumns     = []string{"id"}
	proxyGeneratedColumns      = []string{}
)

type (
	// ProxySlice is an alias for a slice of pointers to Proxy.
	// This should almost always be used instead of []Proxy.
	ProxySlice []*Proxy
	// ProxyHook is the signature for custom Proxy hook methods
	ProxyHook func(context.Context, boil.ContextExecutor, *Proxy) error

	proxyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	proxyType                 = reflect.TypeOf(&Proxy{})
	proxyMapping              = queries.MakeStructMapping(proxyType)
	proxyPrimaryKeyMapping, _ = queries.BindMapping(proxyType, proxyMapping, proxyPrimaryKeyColumns)
	proxyInsertCacheMut       sync.RWMutex
	proxyInsertCache          = make(map[string]insertCache)
	proxyUpdateCacheMut       sync.RWMutex
	proxyUpdateCache          = make(map[string]updateCache)
	proxyUpsertCacheMut       sync.RWMutex
	proxyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var proxyAfterSelectHooks []ProxyHook

var proxyBeforeInsertHooks []ProxyHook
var proxyAfterInsertHooks []ProxyHook

var proxyBeforeUpdateHooks []ProxyHook
var proxyAfterUpdateHooks []ProxyHook

var proxyBeforeDeleteHooks []ProxyHook
var proxyAfterDeleteHooks []ProxyHook

var proxyBeforeUpsertHooks []ProxyHook
var proxyAfterUpsertHooks []ProxyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Proxy) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Proxy) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Proxy) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Proxy) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Proxy) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Proxy) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Proxy) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Proxy) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Proxy) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range proxyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProxyHook registers your hook function for all future operations.
func AddProxyHook(hookPoint boil.HookPoint, proxyHook ProxyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		proxyAfterSelectHooks = append(proxyAfterSelectHooks, proxyHook)
	case boil.BeforeInsertHook:
		proxyBeforeInsertHooks = append(proxyBeforeInsertHooks, proxyHook)
	case boil.AfterInsertHook:
		proxyAfterInsertHooks = append(proxyAfterInsertHooks, proxyHook)
	case boil.BeforeUpdateHook:
		proxyBeforeUpdateHooks = append(proxyBeforeUpdateHooks, proxyHook)
	case boil.AfterUpdateHook:
		proxyAfterUpdateHooks = append(proxyAfterUpdateHooks, proxyHook)
	case boil.BeforeDeleteHook:
		proxyBeforeDeleteHooks = append(proxyBeforeDeleteHooks, proxyHook)
	case boil.AfterDeleteHook:
		proxyAfterDeleteHooks = append(proxyAfterDeleteHooks, proxyHook)
	case boil.BeforeUpsertHook:
		proxyBeforeUpsertHooks = append(proxyBeforeUpsertHooks, proxyHook)
	case boil.AfterUpsertHook:
		proxyAfterUpsertHooks = append(proxyAfterUpsertHooks, proxyHook)
	}
}

// One returns a single proxy record from the query.
func (q proxyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Proxy, error) {
	o := &Proxy{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dm: failed to execute a one query for proxy")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Proxy records from the query.
func (q proxyQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProxySlice, error) {
	var o []*Proxy

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dm: failed to assign all query results to Proxy slice")
	}

	if len(proxyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Proxy records in the query.
func (q proxyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dm: failed to count proxy rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q proxyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dm: failed to check if proxy exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *Proxy) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// InstagramAccounts retrieves all the instagram_account's InstagramAccounts with an executor.
func (o *Proxy) InstagramAccounts(mods ...qm.QueryMod) instagramAccountQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"instagram_account\".\"proxy_id\"=?", o.ID),
	)

	return InstagramAccounts(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (proxyL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProxy interface{}, mods queries.Applicator) error {
	var slice []*Proxy
	var object *Proxy

	if singular {
		object = maybeProxy.(*Proxy)
	} else {
		slice = *maybeProxy.(*[]*Proxy)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &proxyR{}
		}
		args = append(args, object.AccountID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &proxyR{}
			}

			for _, a := range args {
				if a == obj.AccountID {
					continue Outer
				}
			}

			args = append(args, obj.AccountID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`account`),
		qm.WhereIn(`account.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for account")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account")
	}

	if len(proxyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.Proxies = append(foreign.R.Proxies, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.ID {
				local.R.Account = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.Proxies = append(foreign.R.Proxies, local)
				break
			}
		}
	}

	return nil
}

// LoadInstagramAccounts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (proxyL) LoadInstagramAccounts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProxy interface{}, mods queries.Applicator) error {
	var slice []*Proxy
	var object *Proxy

	if singular {
		object = maybeProxy.(*Proxy)
	} else {
		slice = *maybeProxy.(*[]*Proxy)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &proxyR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &proxyR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`instagram_account`),
		qm.WhereIn(`instagram_account.proxy_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load instagram_account")
	}

	var resultSlice []*InstagramAccount
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice instagram_account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on instagram_account")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for instagram_account")
	}

	if len(instagramAccountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.InstagramAccounts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &instagramAccountR{}
			}
			foreign.R.Proxy = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ProxyID) {
				local.R.InstagramAccounts = append(local.R.InstagramAccounts, foreign)
				if foreign.R == nil {
					foreign.R = &instagramAccountR{}
				}
				foreign.R.Proxy = local
				break
			}
		}
	}

	return nil
}

// SetAccount of the proxy to the related item.
// Sets o.R.Account to related.
// Adds o to related.R.Proxies.
func (o *Proxy) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"proxy\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, proxyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.ID
	if o.R == nil {
		o.R = &proxyR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	if related.R == nil {
		related.R = &accountR{
			Proxies: ProxySlice{o},
		}
	} else {
		related.R.Proxies = append(related.R.Proxies, o)
	}

	return nil
}

// AddInstagramAccounts adds the given related objects to the existing relationships
// of the proxy, optionally inserting them as new records.
// Appends related to o.R.InstagramAccounts.
// Sets related.R.Proxy appropriately.
func (o *Proxy) AddInstagramAccounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*InstagramAccount) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ProxyID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"instagram_account\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"proxy_id"}),
				strmangle.WhereClause("\"", "\"", 2, instagramAccountPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ProxyID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &proxyR{
			InstagramAccounts: related,
		}
	} else {
		o.R.InstagramAccounts = append(o.R.InstagramAccounts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &instagramAccountR{
				Proxy: o,
			}
		} else {
			rel.R.Proxy = o
		}
	}
	return nil
}

// SetInstagramAccounts removes all previously related items of the
// proxy replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Proxy's InstagramAccounts accordingly.
// Replaces o.R.InstagramAccounts with related.
// Sets related.R.Proxy's InstagramAccounts accordingly.
func (o *Proxy) SetInstagramAccounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*InstagramAccount) error {
	query := "update \"instagram_account\" set \"proxy_id\" = null where \"proxy_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.InstagramAccounts {
			queries.SetScanner(&rel.ProxyID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Proxy = nil
		}
		o.R.InstagramAccounts = nil
	}

	return o.AddInstagramAccounts(ctx, exec, insert, related...)
}

// RemoveInstagramAccounts relationships from objects passed in.
// Removes related items from R.InstagramAccounts (uses pointer comparison, removal does not keep order)
// Sets related.R.Proxy.
func (o *Proxy) RemoveInstagramAccounts(ctx context.Context, exec boil.ContextExecutor, related ...*InstagramAccount) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ProxyID, nil)
		if rel.R != nil {
			rel.R.Proxy = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("proxy_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.InstagramAccounts {
			if rel != ri {
				continue
			}

			ln := len(o.R.InstagramAccounts)
			if ln > 1 && i < ln-1 {
				o.R.InstagramAccounts[i] = o.R.InstagramAccounts[ln-1]
			}
			o.R.InstagramAccounts = o.R.InstagramAccounts[:ln-1]
			break
		}
	}

	return nil
}

// Proxies retrieves all the records using an executor.
func Proxies(mods ...qm.QueryMod) proxyQuery {
	mods = append(mods, qm.From("\"proxy\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"proxy\".*"})
	}

	return proxyQuery{q}
}

// FindProxy retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProxy(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Proxy, error) {
	proxyObj := &Proxy{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"proxy\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, proxyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dm: unable to select from proxy")
	}

	if err = proxyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return proxyObj, err
	}

	return proxyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Proxy) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dm: no proxy provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(proxyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	proxyInsertCacheMut.RLock()
	cache, cached := proxyInsertCache[key]
	proxyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			proxyAllColumns,
			proxyColumnsWithDefault,
			proxyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(proxyType, proxyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(proxyType, proxyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"proxy\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"proxy\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dm: unable to insert into proxy")
	}

	if !cached {
		proxyInsertCacheMut.Lock()
		proxyInsertCache[key] = cache
		proxyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Proxy.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Proxy) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	proxyUpdateCacheMut.RLock()
	cache, cached := proxyUpdateCache[key]
	proxyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			proxyAllColumns,
			proxyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dm: unable to update proxy, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"proxy\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, proxyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(proxyType, proxyMapping, append(wl, proxyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to update proxy row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: failed to get rows affected by update for proxy")
	}

	if !cached {
		proxyUpdateCacheMut.Lock()
		proxyUpdateCache[key] = cache
		proxyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q proxyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to update all for proxy")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to retrieve rows affected for proxy")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProxySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), proxyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"proxy\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, proxyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to update all in proxy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to retrieve rows affected all in update all proxy")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Proxy) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dm: no proxy provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(proxyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	proxyUpsertCacheMut.RLock()
	cache, cached := proxyUpsertCache[key]
	proxyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			proxyAllColumns,
			proxyColumnsWithDefault,
			proxyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			proxyAllColumns,
			proxyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dm: unable to upsert proxy, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(proxyPrimaryKeyColumns))
			copy(conflict, proxyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"proxy\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(proxyType, proxyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(proxyType, proxyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dm: unable to upsert proxy")
	}

	if !cached {
		proxyUpsertCacheMut.Lock()
		proxyUpsertCache[key] = cache
		proxyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Proxy record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Proxy) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dm: no Proxy provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), proxyPrimaryKeyMapping)
	sql := "DELETE FROM \"proxy\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to delete from proxy")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: failed to get rows affected by delete for proxy")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q proxyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dm: no proxyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to delete all from proxy")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: failed to get rows affected by deleteall for proxy")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProxySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(proxyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), proxyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"proxy\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, proxyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dm: unable to delete all from proxy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dm: failed to get rows affected by deleteall for proxy")
	}

	if len(proxyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Proxy) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProxy(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProxySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProxySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), proxyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"proxy\".* FROM \"proxy\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, proxyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dm: unable to reload all in ProxySlice")
	}

	*o = slice

	return nil
}

// ProxyExists checks if the Proxy row exists.
func ProxyExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"proxy\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dm: unable to check if proxy exists")
	}

	return exists, nil
}
